### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by himito** [microservices-community/microservices-2022#1]
Dear @thesave,

I was wondering how I could check the output of the compilation process of the website. In the morning, I pushed some modifications, but they are not reflected on the website (6 hours have passed since the push).

Thank you in advance.
Jaime

**Comment by thesave** [comment]
Hi @himito,

You can check the result of the compilation locally by running the command `make serve` at the root of the repo. You need to have `make` and ruby installed. I checked your commit myself and everything seems fine with the commit — I can see your modification running the site locally.
The CICD pipeline also seems to have picked up your commit correctly, 6h ago. I re-triggered the build of the image, but it could be the host which is not deploying the new version.
I'd say we can wait a couple of hours and, if we do not see any changes, I'd kindly ask @fmontesi to check if the host is correctly pulling the new images for deployment.

**Comment by himito** [comment]
Hi @thesave,

thank you a lot  for your prompt answer! We will wait :)

Yes, I have a dev environment and all it's OK locally, but as you say, they are not reflected in prod.

Have a nice day.
Jaime

**Comment by himito** [comment]
Hi @thesave,
Sorry to bother you again, did you get any news?
Thank you in advance.
Jaime

**Comment by thesave** [comment]
Hi @himito,

Thanks for the nudge. I'll try to get in contact with @fmontesi and solve this issue ASAP.
I'll let you know as soon as I have some news.

**Comment by fmontesi** [comment]
Hi all,

Something got stuck in the devops pipeline, I've given it a manual nudge. Is the right website showing now?

**Comment by thesave** [comment]
Thanks! It looks fine to me. Do you agree, @himito?

**Comment by himito** [comment]
Hi all,

Yes !!!!! 
Thank you a lot ! @thesave and @fmontesi  !

Have a nice day,
Jaime
